### ISSUE TITLE
Vendoring failure upon Deno 1.22.0 upgrade

### ISSUE THREAD

**Issue by cdoremus** [exhibitionist-digital/ultra#123]
I upgraded to Deno 1.22.0 and found that `vendor.test.ts` failed. The error appears in the `replaceImportStringLiteral()` function of `vendor.ts` when vendoring the import for the _invariant_ library (see below). This seemed to occur because the `StringLiteral` argument value was "/v78/invariant@2.2.4/X-ZGVwczpyZWFjdEAxOC4xLjA/es2021/invariant.js" which is not a valid URL (as the error message points out).

This is the output when the test failure occurred:
```
Vendoring https://cdn.esm.sh/invariant@2.2.4?target=es2021&pin=v78&deps=react@18.1.0
vendor mapping ...----- output end -----
  should create vendor map with imports prop ... FAILED (8s)
    error: TypeError: Invalid URL
        const url = new URL(value);
                    ^
        at Object.opSync (deno:core/01_core.js:172:12)
        at opUrlParse (deno:ext/url/00_url.js:48:27)
        at new URL (deno:ext/url/00_url.js:322:20)
        at VendorVisitor.replaceImportStringLiteral (file:///home/craig/git/deno/ultra_fork/src/ast/vendor.ts:38:17)
        at VendorVisitor.visitExportAllDeclaration (file:///home/craig/git/deno/ultra_fork/src/ast/vendor.ts:14:24)
        at VendorVisitor.visitModuleDeclaration (https://cdn.esm.sh/v78/@swc/core@1.2.171/deno/Visitor.js:2:1718)
        at VendorVisitor.visitModuleItem (https://cdn.esm.sh/v78/@swc/core@1.2.171/deno/Visitor.js:2:1227)
        at Array.map (<anonymous>)
        at VendorVisitor.visitModuleItems (https://cdn.esm.sh/v78/@swc/core@1.2.171/deno/Visitor.js:2:887)
        at VendorVisitor.visitModule (https://cdn.esm.sh/v78/@swc/core@1.2.171/deno/Visitor.js:2:771)
FAILED (8s)

 ERRORS 

vendor mapping => https://deno.land/std@0.136.0/testing/_test_suite.ts:187:10
error: Error: 1 test step failed.
    at runTest (deno:runtime/js/40_testing.js:813:11)
    at async Object.runTests (deno:runtime/js/40_testing.js:1116:22)

 FAILURES 

vendor mapping => https://deno.land/std@0.136.0/testing/_test_suite.ts:187:10

test result: FAILED. 9 passed (22 steps); 1 failed (1 step); 0 ignored; 0 measured; 0 filtered out (11s)
```
The same error occurred when running `deno task vendor` in the workspace folder.

**Comment by mashaal** [comment]
This seems to be a regression in esm.sh -- I have added a quick hotfix to our WIP v2 branch, if you are blocked by this now, try our new build script here...

https://raw.githubusercontent.com/exhibitionist-digital/ultra/v2-prepare/src/deno/build.ts

```bash
root=https://my-site.deno.dev deno run -A https://raw.githubusercontent.com/exhibitionist-digital/ultra/v2-prepare/src/deno/build.ts
```

**Comment by cdoremus** [comment]
This seems to be working now in Deno v1.22 as `esm.sh` must have been fixed,

**Comment by Rin-Akaia-eth** [comment]
I have the same error but for the `deno.land/x` namespace

deno 1.22.2 (release, aarch64-apple-darwin)
v8 10.3.174.6
typescript 4.6.2

```
Warning deno task is unstable and may drastically change in the future
Task vendor importMap=importMap.json deno run -A --unstable --no-check https://deno.land/x/ultra@v0.8.2/vendor.ts
Vendoring https://deno.land/x/ceratosaur@1.0.0-beta-8.1/mod.ts?target=es2021&no-check=true
error: Uncaught (in promise) TypeError: Invalid URL
      const url = new URL(value);
                  ^
    at Object.opSync (deno:core/01_core.js:172:12)
    at opUrlParse (deno:ext/url/00_url.js:48:27)
    at new URL (deno:ext/url/00_url.js:322:20)
    at https://deno.land/x/ultra@v0.8.2/src/transform.ts:133:19
    at Array.forEach (<anonymous>)
    at vendor (https://deno.land/x/ultra@v0.8.2/src/transform.ts:128:12)
    at vendor (https://deno.land/x/ultra@v0.8.2/src/vendor.ts:46:11)
    at async https://deno.land/x/ultra@v0.8.2/vendor.ts:5:18
```
