### ISSUE TITLE
Unable to use `react-inspector` inside ultra app

### ISSUE THREAD

**Issue by cowboyd** [exhibitionist-digital/ultra#129]
Hi there,

I'm trying to use `react-inspector` to view `.json` files inside a toy ultra app and I'm getting a weird error. It's probably pretty common, but since this was my first time using ultra, I'm not exactly sure where to look.

I've created this repo here https://github.com/cowboyd/ultra-react-inspector

And if you run it, this is the error you get:

```
$ deno task dev
Warning deno task is unstable and may drastically change in the future
Task dev port=8008 mode=dev deno run -A --no-check --unstable --location http://localhost:8008 server.ts
Download https://esm.sh/react-inspector@5.1.1
Download https://esm.sh/v83/react-inspector@5.1.1/deno/react-inspector.js
Download https://esm.sh/v83/@types/react-inspector@latest/index.d.ts
Download https://esm.sh/v83/@types/react-inspector@4.0.2/index.d.ts
Download https://esm.sh/v83/is-dom@1.1.0/deno/is-dom.js
Download https://esm.sh/v83/prop-types@15.8.1/deno/prop-types.js
Download https://esm.sh/v83/react@17.0.2/deno/react.js
Download https://esm.sh/v83/is-object@1.0.2/deno/is-object.js
Download https://esm.sh/v83/is-window@1.0.2/deno/is-window.js
Download https://esm.sh/v83/@types/react@18.0.9/index.d.ts
Download https://esm.sh/v83/csstype@3.1.0/index.d.ts
Download https://esm.sh/v83/@types/react@18.0.9/global.d.ts
Download https://esm.sh/v83/@types/prop-types@15.7.5/index.d.ts
Download https://esm.sh/v83/@types/scheduler@0.16.2/tracing.d.ts
Ultra running http://localhost:8008
Download http://localhost:8008/app.js?ts=1653803734816
Transpile src/app.tsx in 53.06ms
Download http://localhost:8008/component.js?ts=16538037349
Transpile src/component.tsx in 1.11ms
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (https://esm.sh/v83/react@17.0.2/deno/react.js:2:4838)
    at n.useMemo (https://esm.sh/v83/react@17.0.2/deno/react.js:2:6821)
    at ThemeAcceptor (https://esm.sh/v83/react-inspector@5.1.1/deno/react-inspector.js:4:5707)
    at Ln (https://cdn.esm.sh/v78/react-dom@18.1.0/deno/server.js:12:10900)
    at pt (https://cdn.esm.sh/v78/react-dom@18.1.0/deno/server.js:12:11639)
    at D (https://cdn.esm.sh/v78/react-dom@18.1.0/deno/server.js:12:13848)
    at pt (https://cdn.esm.sh/v78/react-dom@18.1.0/deno/server.js:12:11866)
    at D (https://cdn.esm.sh/v78/react-dom@18.1.0/deno/server.js:12:13848)
    at pt (https://cdn.esm.sh/v78/react-dom@18.1.0/deno/server.js:12:11866)
    at D (https://cdn.esm.sh/v78/react-dom@18.1.0/deno/server.js:12:13848)
Download http://localhost:8008/app.js?ts=1653803734897
```

Here is the react error https://reactjs.org/docs/error-decoder.html?invariant=321

Any ideas?

**Comment by mashaal** [comment]
If you change the import-map value to `https://esm.sh/react-inspector@5.1.1?deps=react@18`, it does seem to work. This is a common issue with other React deps that haven't updated their deps to react18 yet.
