### ISSUE TITLE
#418 Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by cameronelliott** [exhibitionist-digital/ultra#130]
Hi, when I run the directions from the docs:
```
git clone https://github.com/exhibitionist-digital/create-ultra-app
cd create-ultra-app
deno task dev
```

And then load the page in my browser: http://localhost:8000
I do see the cute heading '@__@' in yellow, but, 
I also get these errors in my console:
```
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at kh (react-dom.js:7:11406)
    at Uk (react-dom.js:9:46863)
    at Tk (react-dom.js:9:40832)
    at Sk (react-dom.js:9:40741)
    at Hk (react-dom.js:9:40590)
    at Fk (react-dom.js:9:35569)
    at J (scheduler.js:2:2244)
    at R (scheduler.js:2:2621)
kh @ react-dom.js:7
Uk @ react-dom.js:9
Tk @ react-dom.js:9
Sk @ react-dom.js:9
Hk @ react-dom.js:9
Fk @ react-dom.js:9
J @ scheduler.js:2
R @ scheduler.js:2
setTimeout (async)
__setImmediate$ @ scheduler.js:2
S @ scheduler.js:2
I @ scheduler.js:2
r.unstable_scheduleCallback @ scheduler.js:2
Ek @ react-dom.js:9
Ck @ react-dom.js:9
dl @ react-dom.js:9
de.hydrateRoot @ react-dom.js:9
(anonymous) @ (index):1
react-dom.js:9 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Uk (react-dom.js:9:46533)
    at Tk (react-dom.js:9:40832)
    at Sk (react-dom.js:9:40741)
    at Hk (react-dom.js:9:40590)
    at Mk (react-dom.js:9:36852)
    at Fk (react-dom.js:9:35794)
    at J (scheduler.js:2:2244)
    at R (scheduler.js:2:2621)
Uk @ react-dom.js:9
Tk @ react-dom.js:9
Sk @ react-dom.js:9
Hk @ react-dom.js:9
Mk @ react-dom.js:9
Fk @ react-dom.js:9
J @ scheduler.js:2
R @ scheduler.js:2
setTimeout (async)
__setImmediate$ @ scheduler.js:2
S @ scheduler.js:2
I @ scheduler.js:2
r.unstable_scheduleCallback @ scheduler.js:2
Ek @ react-dom.js:9
Ck @ react-dom.js:9
dl @ react-dom.js:9
de.hydrateRoot @ react-dom.js:9
(anonymous) @ (index):1
```

Those errors link to:
https://reactjs.org/docs/error-decoder.html/?invariant=423
https://reactjs.org/docs/error-decoder.html/?invariant=418

Which are respectively for:

**1. There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
2. Hydration failed because the initial UI does not match what was rendered on the server.**

Any thought why this errors are happening on an unmodified clone of the example repo?

Thank you

**Comment by nnmrts** [comment]
This seems to be a react or react-dom issue. If you upgrade to react@next and react-dom@next, this error goes away. I don't know why and I got that solution from an issue in the react repo I can't currently find again, but yeah, it works.
